test_app/urls.py
from django.urls import path

from . import views

app_name = 'test_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new-topic/', views.new_topic, name="new_topic"),
    path('new-entry/<int:topic_id>/', views.new_entry, name="new_entry"),
    path('edit-entry/<int:entry_id>/', views.edit_entry, name="edit_entry"),
]

test_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('test_app.urls')),
    path("users/", include('users.urls'))
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path('login-user/', views.login_user, name="login_user"),
    path("logout-user/", views.logout_user, name="logout_user"),
    path("register/", views.register, name="register")
]

test_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topics(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

class Entry(models.Model):
    topic = models.ForeignKey(Topics, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

test_app/forms.py
from django import forms
from .models import Topics, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topics
        fields = ['text']
        labels = {'text':""}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

test_app/views.py
from django.shortcuts import render, redirect
from .models import Topics, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.
def index(request):
    return render(request, 'test_app/index.html')

@login_required
def topics(request):
    topics = Topics.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, "test_app/topics.html", context)

@login_required
def topic(request, topic_id):
    topic = Topics.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {"topic":topic, "entries":entries}
    return render(request, "test_app/topic.html", context)

@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect("test_app:topics")

    context = {'form':form}
    return render(request, 'test_app/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topics.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect("test_app:topic", topic_id=topic_id)

    context={"form":form, "topic":topic}
    return render(request, 'test_app/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != "POST":
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("test_app:topic", topic_id=topic.id)

    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request, "test_app/edit_entry.html", context)

users/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def login_user(request):
    if request.method != "POST":
        form = AuthenticationForm()
    else:
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('test_app:index')
    context = {'form':form}
    return render(request, "registration/login.html", context)

def logout_user(request):
    logout(request)
    context = {}
    return render(request, "registration/logout.html", context)

def register(request):
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect("test_app:index")

    context = {"form":form}
    return render(request, "registration/register.html", context)

test_app/templates/test_app/default.html
<!DOCTYPE html>
{% load bootstrap4 %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fill=no">
    <title>Test Site</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>

<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'test_app:index' %}">Learning Log</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'test_app:topics' %}">Topics</a>
        </li>
        {% if user.is_authenticated %}
        <li>
          <p1 class="nav-link">Hello {{ user.username }} | </p1>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout_user' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login_user' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
        </li>
        {% endif %}
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" aria-disabled="true">Disabled</a>-->
<!--        </li>-->
      </ul>
    </div>
  </div>
</nav>
<main role="main" class="container">
  <div class="pb-2 mb-2 border-bottom">
    {% block page_header%}{% endblock page_header %}
  </div>
  <div>
    {% block content %}{% endblock content %}
  </div>
</main>
</body>
</html>

test_app/templates/test_app/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Entry</title>
</head>
<body>
{% extends 'test_app/default.html' %}
{% load bootstrap4 %}

{% block page_header %}
<h2>
    Edit an Entry For
    <a href="{% url 'test_app:topic' topic.id %}">{{ topic }}</a>
</h2>
{% endblock page_header %}

{% block content %}

<form method="post" action="{% url 'test_app:edit_entry' entry.id %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">Save Changes</button>
    {% endbuttons %}
</form>

{% endblock %}
</body>
</html>

test_app/templates/test_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home page</title>
</head>
<body>
{% extends "test_app/default.html" %}

{% block page_header %}

<div class="jumbotron">
  <h1 class="display-4">The Ultimate Test Site</h1>
  <p class="lead">This site is used to test any HTML things and web designing things</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="{% url 'users:register' %}" role="button">Register>></a>
  </p>
</div>

{% endblock page_header %}
</body>
</html>

test_app/templates/test_app/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Entry</title>
</head>
<body>
{% extends 'test_app/default.html' %}
{% load bootstrap4 %}

{% block page_header %}
<h2>
    Add a New Entry For
    <a href="{% url 'test_app:topic' topic.id %}">{{ topic }}</a>
</h2>
{% endblock page_header %}

{% block content %}

<form method="post" action="{% url 'test_app:new_entry' topic.id %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">Add Entry!</button>
    {% endbuttons %}
</form>

{% endblock %}
</body>
</html>

test_app/templates/test_app/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>new topic</title>
</head>
<body>
{% extends 'test_app/default.html' %}
{% load bootstrap4 %}

{% block page_header %}
<h2>Add a New Topic</h2>
{% endblock page_header %}

{% block content %}

<form method="post" action="{% url 'test_app:new_topic' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">Add Topic!</button>
    {% endbuttons %}
</form>

{% endblock %}
</body>
</html>

test_app/templates/test_app/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Entries</title>
</head>
<body>
{% extends "test_app/default.html" %}

{% block page_header %}
<h3>Entries for {{ topic }}:</h3>
{% endblock page_header %}

{% block content %}

{% for entry in entries %}
<div class="class mb-3">
    <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small>
            <a href="{% url 'test_app:edit_entry' entry.id %}">Edit</a>
        </small>
    </h4>
    <div class="card-body">
        {{ entry.text|linebreaks }}
    </div>
</div>
{% empty %}
<p>No Entries Yet!</p>
{% endfor %}

<h2>
    <a href="{% url 'test_app:new_entry' topic.id %}">Add Entry!</a>
</h2>

{% endblock content %}
</body>
</html>

test_app/templates/test_app/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topics</title>
</head>
<body>
{% extends "test_app/default.html" %}

{% block page_header %}
<h2>Topics</h2>
{% endblock page_header %}

{% block content %}

<p>Topics</p>

<ul>
    {% for topic in topics %}
    <li>
        <h3>
            <a href="{% url 'test_app:topic' topic.id %}">{{ topic }}</a>
        </h3>
    </li>
    {% empty %}
    <li>
        <h3>No Topics Yet!</h3>
    </li>
    {% endfor %}
</ul>

<br>

<h3>
    <a href="{% url 'test_app:new_topic' %}">Add Another Topic!</a>
</h3>
{% endblock content %}
</body>
</html>